# This rule is not used by the project kbinit itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the score.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kbinit
    app.kubernetes.io/managed-by: kustomize
  name: resourceclaim-editor-role
rules:
- apiGroups:
  - score.dev
  resources:
  - resourceclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - score.dev
  resources:
  - resourceclaims/status
  verbs:
  - get
