---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - score.dev
  resources:
  - resourceclaims
  - workloadexposures
  - workloadplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - score.dev
  resources:
  - resourceclaims/status
  - workloads
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - score.dev
  resources:
  - workloadexposures/finalizers
  - workloadplans/finalizers
  - workloads/finalizers
  verbs:
  - update
- apiGroups:
  - score.dev
  resources:
  - workloadexposures/status
  verbs:
  - get
  - patch
  - update
  - watch
- apiGroups:
  - score.dev
  resources:
  - workloadplans/status
  - workloads/status
  verbs:
  - get
  - patch
  - update
