apiVersion: score.dev/v1b1
kind: Workload
metadata:
  name: hello-web
  namespace: default
spec:
  containers:
    app:
      image: ghcr.io/score-spec/sample-app-gif:main
      variables:
        PG_CONNECTION_STRING: "postgresql://${resources.db.username}:${resources.db.password}@${resources.db.host}:${resources.db.port}/${resources.db.database}?sslmode=disable"
  service:
    ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP
  resources:
    db:
      type: postgres
