apiVersion: v1
kind: Namespace
metadata:
  name: score-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-config
  namespace: score-system
data:
  config.yaml: |
    apiVersion: score.dev/v1b1
    kind: OrchestratorConfig
    metadata:
      name: test-config
      version: "1.0.0"
    spec:
      profiles:
      - name: web-service
        description: "Web service profile"
        backends:
        - backendId: k8s-web-1
          runtimeClass: kubernetes
          template:
            kind: manifests
            ref: "registry.example.com/templates/web@sha256:abc123"
            values:
              replicas: 3
          priority: 100
          version: "1.0.0"
      - name: database-service
        description: "Database service profile"
        backends:
        - backendId: k8s-db-1
          runtimeClass: kubernetes
          template:
            kind: manifests
            ref: "registry.example.com/templates/db@sha256:def456"
            values:
              storage: "10Gi"
          priority: 90
          version: "1.0.0"
      provisioners:
      - type: postgres
        provisioner: postgres-operator
        classes:
        - name: small
          description: "Small database"
          parameters:
            cpu: "500m"
            memory: "1Gi"
            storage: "10Gi"
        - name: large
          description: "Large database"
          parameters:
            cpu: "2000m"
            memory: "4Gi"
            storage: "100Gi"
      defaults:
        profile: web-service