apiVersion: score.dev/v1b1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/name: kbinit
    app.kubernetes.io/managed-by: kustomize
  name: workload-sample
  namespace: score-system
spec:
  profile: web-service
  containers:
    app:
      image: nginx:latest
  resources:
    db:
      type: postgres
